### ISSUE TITLE
Increase concurrent job

### ISSUE THREAD

**Issue by MitchK** [travis-ci/enterprise-installation#12]
Hi! What would be the preferred way to increase the number of concurrent builds per worker node?

Attaching another worker works great for increasing the number of total concurrent builds. As we have huge and long-running builds (up to half a day), we would like to use bigger worker nodes with more concurrent builds per worker node.

Cheers,
Michael

**Comment by joshk** [comment]
Hi @MitchK 

We have just released a new version of our worker, which allows for familiar ways to increase the running concurrent jobs per host.

For this to work though we need to get your Platform upgraded to the latest version.

I'm going to close this issue for now, but please message us and we can get everything rolling.

Have an awesome day

Josh
