### ISSUE TITLE
Zombie builds in queue

### ISSUE THREAD

**Issue by MitchK** [travis-ci/enterprise-installation#13]
Hi, we currently have zombie builds in queue (for two days). We currently don't have a worker running that supports iOS builds.

![screen shot 2015-05-01 at 10 20 44](https://cloud.githubusercontent.com/assets/2472064/7428212/62abcb86-efec-11e4-8199-5c092c7d1993.jpg)

How can we avoid this and clean this up? Thanks

**Comment by joshk** [comment]
Hi Mitch

We are planning on an upgrade to the Travis application which will make cancelling queued jobs easier.

Until then, we can put together a small script which can take care of this for you.

Please email us and we can get this resolved for you.

Have an awesome day

Josh
