### ISSUE TITLE
Increase Job Timeouts

### ISSUE THREAD

**Issue by MitchK** [travis-ci/enterprise-installation#18]
Hi, is is possible to increase the job timeouts?

Cheers, Michael

**Comment by joshk** [comment]
Hi @MitchK

We have just released a new version of our worker, which allows for a simpler way to increase the Job timeouts.

For this to work though we need to get your Platform upgraded to the latest version.

I'm going to close this issue for now, but please message us and we can get everything rolling.

Have an awesome day

Josh
