### ISSUE TITLE
Ability to kick off a new build w/o pushing

### ISSUE THREAD

**Issue by msimerson** [travis-ci/enterprise-installation#4]
I just signed up for AppVeyor and was delighted to find that on new repos that I added, I was able to kick off a new build immediately from the web ui, without having to push a new commit to the repo. That's a very welcoming feature worth considering.

**Comment by joshk** [comment]
Thanks for the suggestion Matt. We actually have this in the works.

I'm going to close this issue for now as this repo is just for Enterprise installation.

Have an awesome day.
