### ISSUE TITLE
node 0.12 binary not available yet?

### ISSUE THREAD

**Issue by msimerson** [travis-ci/enterprise-installation#5]
````
mv: cannot move `/home/travis/.nvm/bin/node-v0.12.0-linux-x64' to `/home/travis/.nvm/versions/v0.12.0': No such file or directory
Binary download failed, trying source.
````
I've run `te pull` and `te start` on the Travis worker, so I think I'm up-to-date. nvm does build node 0.12 from sources, but it'd be much better to have the jobs run in 1m instead of 13m. Anything else I should be trying? Is there another place I should be posting such issues?

**Comment by joshk** [comment]
Hi @msimerson, I think this is related to the build environment containers, and not the Enterprise containers.

Have you tried downloading new build environment containers?

**Comment by msimerson** [comment]
Ch-ching. Right you are. Next question, would it be mostly safe to put something like this in cron weekly?

```sh
langs='go node-js perl'
tag=latest
for lang in $langs; do
  docker pull quay.io/travisci/travis-$lang:$tag
  docker tag quay.io/travisci/travis-$lang:$tag travis:$lang
done
te start
```

**Comment by joshk** [comment]
@msimerson well, that is up to you, but I am not sure if I would recommend it as the change in images could have unintended consequences for your users.

There are pros and cons either way.
