### ISSUE TITLE
Docs update.

### ISSUE THREAD

**Issue by msimerson** [travis-ci/enterprise-installation#6]
On [this blog page](http://blog.travis-ci.com/support_for_go_c_and_cpp/), the first repo cited as using Travis with Go (peterbourgon/diskv) has a broken link as that repo is now using Drone.io. That post should be updated.

**Comment by joshk** [comment]
Sorry @msimerson, can you please create this issue on our main issue tracker: https://github.com/travis-ci/travis-ci/issues
