### ISSUE TITLE
Custom root certificate

### ISSUE THREAD

**Issue by MitchK** [travis-ci/enterprise-installation#8]
Hi,

We are currently trying to add our GHE root certificate to ```te-main```. We followed this instructions: https://github.com/travis-ci/enterprise-installation#specifying-a-custom-root-certificate

Which format and file extension should this certificate have?
We tried to place our internal root certificate for GHE in this file (encoded as ASCII PEM): 

```
/etc/travis/ssl/ca-certificates/my_root_certificate.crt
```

and restarted Travis:

```
sudo te start
```

All requests against GHE (e.g. for setting commit status) still fail:

```
$ tail -f /var/log/travis.log
...
[2015-03-30T14:26:47+0000][travis-tasks:tasks] 2015-03-30T14:26:47Z 2816 TID-418 WARN: type=github_status build=127 repo=travis/example-nodejs-1 error=not_updated url=https://github.mycompany.corp/repos/travis/example-nodejs-1/statuses/e2af25e1ea4f2bf01a70cbb0a9385b6977caf613 message=GH request failed
[2015-03-30T14:26:47+0000][travis-tasks:tasks] verb:               :head
[2015-03-30T14:26:47+0000][travis-tasks:tasks] url:                /api/v3/applications/5dd4868f986cffcd3f45/tokens/41b270a1591c45ed5e32ca800f61486ce0b01aa1?client_id=[removed]&client_secret=[removed]
[2015-03-30T14:26:47+0000][travis-tasks:tasks] headers:            {"Authorization"=>[removed]}
[2015-03-30T14:26:47+0000][travis-tasks:tasks] error:              Faraday::SSLError: certificate verify failed
[2015-03-30T14:26:47+0000][travis-tasks:tasks] payload:            {"state":"success","description":"The Travis CI build passed","target_url":"https://travis-ci.mycompany.corp/travis/example-nodejs-1/builds/127","context":"continuous-integration/travis-ci"}
```

Thanks for your help

**Comment by MitchK** [comment]
This manual hack worked for us:
```
$ sudo su
# ssh te-main
...
# curl -k https://certstore.mycompany.corp/ca.crt > /usr/local/share/ca-certificates/ca.crt
# update-ca-certificates
```

**Comment by joshk** [comment]
Thanks for the report @MitchK, and for the solution you are currently using.

@svenfuchs will get back to you shortly so we can figure out a good solution to this.

**Comment by svenfuchs** [comment]
Hi @MitchK 

I am surprised the certificate isn't being picked up. Here's what te-main does at startup time:

```
  local source=/etc/travis/ssl/ca-certificates
  local target=/usr/share/ca-certificates

  if [ -d $source ]; then
    mkdir -p $target
    for cert in $(find $source -type f); do
      ln -s $cert $target/$(basename $cert)
    done

    update-ca-certificates
  fi
```

The only reason I could think of that would make this fail were file permissions, or a certificate that could not be picked up by the system (and thus, Ruby).

After placing your certificate to `/etc/travis/ssl/ca-certificates/my_root_certificate.crt`, and restarting the container with `te start`, could you `ssh te-main` into the container and see if the file has been symlinked to `/usr/share/ca-certificates`? Also, if it's not, could you check the permissions of the source file?

In case this doesn't help, feel free to join chat.travis-ci.com and ping me.

**Comment by MitchK** [comment]
Hi @svenfuchs,

the certificate are symlinked and seem to have the right permissions.
```
root@te-main:~# ls -la /usr/share/ca-certificates
total 24
drwxr-xr-x   4 root root  4096 Mar 31 08:29 .
drwxr-xr-x 133 root root  4096 Mar 31 08:29 ..
lrwxrwxrwx   1 root root    55 Mar 31 08:29 github.mycompany.corp.crt -> /etc/travis/ssl/ca-certificates/github.mycompany.corp.crt
drwxr-xr-x   2 root root 12288 Dec  4 18:01 mozilla
lrwxrwxrwx   1 root root    44 Mar 31 08:29 mycompanyca.cer -> /etc/travis/ssl/ca-certificates/mycompanyca.cer
lrwxrwxrwx   1 root root    44 Mar 31 08:29 mycompanyca.crt -> /etc/travis/ssl/ca-certificates/mycompanyca.crt
lrwxrwxrwx   1 root root    44 Mar 31 08:29 mycompanyca.der -> /etc/travis/ssl/ca-certificates/mycompanyca.der
lrwxrwxrwx   1 root root    44 Mar 31 08:29 mycompanyca.pem -> /etc/travis/ssl/ca-certificates/mycompanyca.pem
drwxr-xr-x   2 root root  4096 Dec  4 18:01 spi-inc.org
```
We tried running ```update-ca-certificates``` but it did not got picked up. 

When I copied it manually to ```/usr/local/share/local/ca-certificates``` instead of ```/usr/share/ca-certificates``` it got picked up.

```
$ sudo su
# ssh te-main
...
# curl -k https://certstore.mycompany.corp/ca.crt > /usr/local/share/ca-certificates/ca.crt
# update-ca-certificates
```

I'll try to set up a clean worker again to can fully reproduce the issue as we experimented a lot on this. I'll keep you posted.

**Comment by svenfuchs** [comment]
Thank you @MitchK!

**Comment by MitchK** [comment]
Hi @svenfuchs ,

When we restart Travis Main using ```te start```, then the certificates are wiped out, I am sure that the behaviours is intented. So weit, so gut.

So after restarting ```te-main```, it should be reproducible:

1. Add ```myawesomeca.crt``` to host machine's directory: 
```
me@host:~$ sudo ls -la /etc/travis/ssl/ca-certificates/
total 12
drwxr-xr-x 2 root root 4096 Apr 27 14:42 .
drwxr-xr-x 4 root root 4096 Mar 30 14:53 ..
-rw-r--r-- 1 root root  989 Apr 27 14:42 myawesomeca.crt
```

2. Restart ```te-main``` using ```sudo te-start```
3. Create a pull request, trigger a build.

=> No status is reported.
=> Travis logs show: 
```
[2015-04-27T14:57:25+0000][travis-tasks:tasks] error:              Faraday::SSLError: certificate verify failed
```

4. SSH to ```te-main````
5. Check if certificate is in ```/usr/share/ca-certificates``` on ```te-main```
```
root@te-main:~# ls -la /usr/share/ca-certificates/
total 24
drwxr-xr-x   4 root root  4096 Apr 27 14:51 .
drwxr-xr-x 133 root root  4096 Apr 27 14:51 ..
drwxr-xr-x   2 root root 12288 Dec  4 18:01 mozilla
lrwxrwxrwx   1 root root    44 Apr 27 14:51 myawesomeca.crt -> /etc/travis/ssl/ca-certificates/myawesomeca.crt
drwxr-xr-x   2 root root  4096 Dec  4 18:01 spi-inc.org
```
6. Run ```update-ca-certificates```

=> No certificate is imported
=> GHE requests still fail


Fix:

7. Soft link the .crt certificate to ```/usr/local/share/ca-certificates/myawesomeca.crt```:
```
root@te-main:~# ln -s /etc/travis/ssl/ca-certificates/myawesomeca.crt /usr/local/share/ca-certificates/myawesomeca.crt
root@te-main:~# ls -la /usr/local/share/ca-certificates/
total 8
drwxrwsr-x  2 root staff 4096 Apr 27 14:57 .
drwxr-xr-x 11 root root  4096 Apr 27 14:57 ..
lrwxrwxrwx  1 root staff   44 Apr 27 14:57 sapnetca.crt -> /etc/travis/ssl/ca-certificates/myawesomeca.crt
```

8. Run ```update-ca-certificates```

=> Certificate is recognised by update-ca-certificates
=> Requests are successful immediately

It seems that ```/usr/share/ca-certificates``` is the wrong directory to store the certificates. What do you think?

**Comment by joshk** [comment]
@MitchK can this issue be closed?
